export enum colors {
  DISPLAY_BLACK = "#000",
  DISPLAY_WHITE = "#FFF",
  DISPLAY_GREEN = "#00FF00",
  DISPLAY_CYAN = "#00FFFF",
  DISPLAY_RED = "#FF0000",
  DISPLAY_MAGENTA = "#FF00FF",
  DISPLAY_YELLOW = "#FFFF00",
}
